### ISSUE TITLE
demo site hacked?

### ISSUE THREAD

**Issue by cklouman** [miniMAC/magic#37]
Hi, my AV software (ESET Nod32 ) yells at me when I try to go to your demo-site (https://minimamente.com/example/magic_animations/)

> This web page contains potentially dangerous content.
> Threat: HTML/ScrInject.B trojan

Maybe something you want to look into. 
Cheers

**Comment by miniMAC** [comment]
Hi @cklouman ! Thanks, but this is a simple page with simple HTML code, are you sure? Can you reproduce it? Thanks

**Comment by cklouman** [comment]
Well, I'm sure insofar that I get the warning every time. I can't guarantee that it's not a false positive. I did some additional tests and found the same warning on your whole domain (https://minimamente.com/). You should probably contact ESET and have them clarify. Sometimes they blacklist whole domains I believe.

**Comment by miniMAC** [comment]
Have you tested with another PC?

**Comment by miniMAC** [comment]
Hi @cklouman i've nothing found. The server is a Unix machine. So, there isn't any malware. I suppose that your Window machine was infected.
Thanks anyway
