### ISSUE TITLE
npm install @minimac/magic.css

### ISSUE THREAD

**Issue by abhisavadiya** [miniMAC/magic#47]
![image](https://user-images.githubusercontent.com/28340316/73941657-a9c9c380-4913-11ea-93ae-79a34190a31c.png)

**Comment by miniMAC** [comment]
You can install magic.css in npm with that url `https://www.npmjs.com/package/magic.css`

You are wrong. You wrote wrong syntax, the correct syntax is: `npm i magic.css`
